[tool.poetry]
name = "app-poetry-1210"
version = "0.1.0"
description = ""
authors = ["KorenbAS78 <KorenbAS78@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
